# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: controller-manager
#   namespace: system
# ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: galera
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: galera-role
  namespace: mike2
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - post
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: galera-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: galera-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
- kind: ServiceAccount
  name: galera-operator-galera
  namespace: mike2
- kind: ServiceAccount
  name: galera
  namespace: mike2
